### ISSUE TITLE
Hello, can you update the touch screen calibration program of xpt2046?

### ISSUE THREAD

**Issue by maozhifeng** [uraich/lv_mpy_examples#1]
Thank you for the perfect project. I used to use version 6.1. Now I want to try the new version. However, there is no touch calibration procedure available. Can you update it? Thank you very much

**Comment by uraich** [comment]
Can you check 
https://github.com/uraich/lv_binding_micropython/tree/colors/lib
There are 2 new scripts: tpcal_landscape.py and tpcal_portrait.py which allow to calibrate the xtp2046 touch panel when running lvgl v7. Please tell me if this works for you.
Depending on your hardware, you may have to change the pin assignments when calling the ili9341 driver and/or the spi port

**Comment by maozhifeng** [comment]
> 您可以检查
> https://github.com/uraich/lv_binding_micropython/tree/colors/lib吗[？](https://github.com/uraich/lv_binding_micropython/tree/colors/lib)
> 有2个新脚本：tpcal_landscape.py和tpcal_portrait.py，它们可以在运行lvgl v7时校准xtp2046触摸面板。请告诉我这是否适合您。
> 根据您的硬件，在调用ili9341驱动程序和/或spi端口时，可能必须更改引脚分配。

Thank you. After testing, your script can perform touch calibration. My devices are ili9341 and xpt2046

> Can you check
> https://github.com/uraich/lv_binding_micropython/tree/colors/lib
> There are 2 new scripts: tpcal_landscape.py and tpcal_portrait.py which allow to calibrate the xtp2046 touch panel when running lvgl v7. Please tell me if this works for you.
> Depending on your hardware, you may have to change the pin assignments when calling the ili9341 driver and/or the spi port

Thank you. After testing, your script can perform touch calibration. My devices are ili9341 and xpt2046

**Comment by maozhifeng** [comment]
> Can you check
> https://github.com/uraich/lv_binding_micropython/tree/colors/lib
> There are 2 new scripts: tpcal_landscape.py and tpcal_portrait.py which allow to calibrate the xtp2046 touch panel when running lvgl v7. Please tell me if this works for you.
> Depending on your hardware, you may have to change the pin assignments when calling the ili9341 driver and/or the spi port

Thank you. After testing, your script can perform touch calibration. My devices are ili9341 and xpt2046

**Comment by maozhifeng** [comment]
But I have one more question. When I debug a transport program using the repl of the Mu editor, the first pass in of the program causes esp32 to restart, and the second time it is passed in, it will be executed. Is this a firmware error?
